name: Deploy Code

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: deploy to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          script: |
            cd datarush/ailocus
            git pull origin prod
            git checkout prod
            cd frontend
<<<<<<< HEAD
            node -v
            echo $USER
=======
            yarn
>>>>>>> cabd9304a6c3585c6a44ccb647cc6ba53c7377a0
            yarn run build
            echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart datarush
